/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import DateBase.Tableo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.Timer;
 
/**
 *
 * @author CASPED
 */
public class DeleteCliente extends javax.swing.JFrame {

    public String cedula;
    public String nombre;
    public String apellido;
    public String telefono;
    public String TipoUsuario;
    public double saldo;
    public String fecha;
    public String vacio="";
    
    public DeleteCliente() {
        initComponents();
        setTitle("Eliminar Cliente");
        setBounds(700, 300, 700, 520);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje2 = new javax.swing.JLabel();
        mensaje1 = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ciField = new javax.swing.JTextField();
        nombreField = new javax.swing.JTextField();
        apellidosField = new javax.swing.JTextField();
        fechaNacField = new javax.swing.JTextField();
        telefonoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mensaje2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        getContentPane().add(mensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 170, 20));

        mensaje1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        mensaje1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(mensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 370, 20));

        mensaje.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 180, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Gadugi", 1, 28)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ELIMINAR CLIENTE DE LA BD");
        jLabel9.setAlignmentX(0.5F);
        jLabel9.setAutoscrolls(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 460, 30));

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        ciField.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        ciField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ciField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ciField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 125, 260, 30));

        nombreField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(nombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 260, 30));

        apellidosField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(apellidosField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 260, 30));

        fechaNacField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(fechaNacField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 260, 30));

        telefonoField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(telefonoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 260, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("CEDULA DE IDENTIDAD:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("APELLIDO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("NACIMIENTO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("TELEFONO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/publictransport/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabel0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Tableo datoscliente = new Tableo();
        
        cedula=ciField.getText();
        
        if(ciField.getText().length()==0){ 
            
            mensaje.setText("Introducir Cedula...");
            mensaje1.setText(vacio);
            mensaje2.setText(vacio);
            
            nombreField.setText(vacio);
            apellidosField.setText(vacio);
            fechaNacField.setText(vacio);
            telefonoField.setText(vacio);
            
        }else{    
            mensaje.setText("Buscando Cliente ["+cedula+"]...");
           
            nombre=datoscliente.getNombre(cedula);
            apellido=datoscliente.getApellido(cedula);
            fecha=datoscliente.getFecha(cedula);
            telefono=datoscliente.getTelefono(cedula);

            nombreField.setText(nombre);
            apellidosField.setText(apellido);
            fechaNacField.setText(fecha);
            telefonoField.setText(telefono);
            System.out.println("bucando cliente con cedula: "+this.cedula);  
            
            ciField.setText(vacio);
            
            if(nombreField.getText().length()==0){ 
                mensaje1.setText("No existe el cliente en la base de datos...");
                mensaje2.setText("Cedula:["+cedula+"]");
            }else{
                mensaje1.setText(vacio);
                mensaje2.setText(vacio);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ciFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        Tableo elimindor = new Tableo();
        
        if(nombreField.getText().length()==0){ 
            mensaje1.setText("ERROR: no se puede eliminar");
            mensaje2.setText(vacio);
        }else{
            elimindor.deleteCliente(this.cedula);
            mensaje1.setText("Elimiando cliente de la base de datos...");
            mensaje2.setText("Cedula: "+cedula);
            
            nombreField.setText(vacio);
            apellidosField.setText(vacio);
            fechaNacField.setText(vacio);
            telefonoField.setText(vacio);
            
            System.out.println("Se elimino la persona con la cedula "+this.cedula);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidosField;
    private javax.swing.JTextField ciField;
    private javax.swing.JTextField fechaNacField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JTextField nombreField;
    private javax.swing.JTextField telefonoField;
    // End of variables declaration//GEN-END:variables
}
